View/75 global changes 1 lil
BlickLabs/project-more pull request #77
Opened 2017-09-29 21:03 UTC by LilianaCanPor

2017-09-29 23:47 UTC, Enrique199413 requested changes

2017-09-29 23:47 UTC, Enrique199413 commented on src/styl/partials/footer.styl
> +  &hove
is correct `hove`?

2017-09-29 23:54 UTC, LilianaCanPor commented on src/styl/partials/footer.styl
> +  &hove
jaja noup

2017-09-30 00:22 UTC, Enrique199413 approved these changes

2017-09-30 00:28 UTC, merged